#
# Copyright (c) 2018 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM centos:7

# Install the Ansible packages:
RUN \
yum install -y --setopt=tsflags=nodocs epel-release && \
yum install -y --setopt=tsflags=nodocs ansible && \
yum clean all

# Create the Ansible user. The unusually high UID is needed because OpenShift
# does't allow lower UID numbers.
RUN useradd -l -u 1000000000 ansible

# Install the oVirt Python SDK so that we can use the oVirt modules:
RUN \
yum install -y --setopt=tsflags=nodocs http://resources.ovirt.org/pub/yum-repo/ovirt-release42.rpm && \
yum install -y --setopt=tsflags=nodocs python-ovirt-engine-sdk4 && \
yum clean all

USER ansible
WORKDIR /home/ansible
