#
# These packages aren't really required by the application, but we need them in
# order to build and run the code Kubernetes API code generators.
#
required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/gengo/examples/defaulter-gen/generators",
]

#
# Reduce the size of the `vendor` directory excluding unused packages, tests and
# other files that aren't needed.
#
[prune]
  go-tests = true
  non-go = true
  unused-packages = true

#
# For the Kubernetes code generator we need to make sure that everything is
# included, as we need the `generate-internal-groups.sh` script to run it.
#
[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false
  unused-packages = false

[[constraint]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "golang.org/x/sync"
  branch = "master"

[[constraint]]
  name = "github.com/ghodss/yaml"
  branch = "master"

[[constraint]]
  name = "github.com/moolitayer/awx-client-go"
  version = "=0.0.4"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[constraint]]
  name = "github.com/yaacov/observer"
  version = "1.5.11"
