// +build !ignore_autogenerated

/*
Copyright (c) 2018 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	batch_v1 "k8s.io/api/batch/v1"
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWXJobAction) DeepCopyInto(out *AWXJobAction) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		if *in == nil {
			*out = nil
		} else {
			*out = new(v1.SecretReference)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWXJobAction.
func (in *AWXJobAction) DeepCopy() *AWXJobAction {
	if in == nil {
		return nil
	}
	out := new(AWXJobAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Delimiters) DeepCopyInto(out *Delimiters) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Delimiters.
func (in *Delimiters) DeepCopy() *Delimiters {
	if in == nil {
		return nil
	}
	out := new(Delimiters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealingAction) DeepCopyInto(out *HealingAction) {
	*out = *in
	if in.Delimiters != nil {
		in, out := &in.Delimiters, &out.Delimiters
		if *in == nil {
			*out = nil
		} else {
			*out = new(Delimiters)
			**out = **in
		}
	}
	if in.AWXJob != nil {
		in, out := &in.AWXJob, &out.AWXJob
		if *in == nil {
			*out = nil
		} else {
			*out = new(AWXJobAction)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.BatchJob != nil {
		in, out := &in.BatchJob, &out.BatchJob
		if *in == nil {
			*out = nil
		} else {
			*out = new(batch_v1.Job)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealingAction.
func (in *HealingAction) DeepCopy() *HealingAction {
	if in == nil {
		return nil
	}
	out := new(HealingAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealingCondition) DeepCopyInto(out *HealingCondition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealingCondition.
func (in *HealingCondition) DeepCopy() *HealingCondition {
	if in == nil {
		return nil
	}
	out := new(HealingCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealingRule) DeepCopyInto(out *HealingRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealingRule.
func (in *HealingRule) DeepCopy() *HealingRule {
	if in == nil {
		return nil
	}
	out := new(HealingRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealingRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealingRuleList) DeepCopyInto(out *HealingRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HealingRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealingRuleList.
func (in *HealingRuleList) DeepCopy() *HealingRuleList {
	if in == nil {
		return nil
	}
	out := new(HealingRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealingRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealingRuleSpec) DeepCopyInto(out *HealingRuleSpec) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]HealingCondition, len(*in))
		copy(*out, *in)
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]HealingAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealingRuleSpec.
func (in *HealingRuleSpec) DeepCopy() *HealingRuleSpec {
	if in == nil {
		return nil
	}
	out := new(HealingRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealingRuleStatus) DeepCopyInto(out *HealingRuleStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealingRuleStatus.
func (in *HealingRuleStatus) DeepCopy() *HealingRuleStatus {
	if in == nil {
		return nil
	}
	out := new(HealingRuleStatus)
	in.DeepCopyInto(out)
	return out
}
