/*
Copyright (c) 2018 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

// This file was automatically generated by informer-gen

package internalversion

import (
	time "time"

	autoheal "github.com/openshift/autoheal/pkg/apis/autoheal"
	clientset_internalversion "github.com/openshift/autoheal/pkg/client/clientset/internalversion"
	internalinterfaces "github.com/openshift/autoheal/pkg/client/informers/internalversion/internalinterfaces"
	internalversion "github.com/openshift/autoheal/pkg/client/listers/autoheal/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HealingRuleInformer provides access to a shared informer and lister for
// HealingRules.
type HealingRuleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.HealingRuleLister
}

type healingRuleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHealingRuleInformer constructs a new informer for HealingRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHealingRuleInformer(client clientset_internalversion.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHealingRuleInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHealingRuleInformer constructs a new informer for HealingRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHealingRuleInformer(client clientset_internalversion.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Autoheal().HealingRules(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Autoheal().HealingRules(namespace).Watch(options)
			},
		},
		&autoheal.HealingRule{},
		resyncPeriod,
		indexers,
	)
}

func (f *healingRuleInformer) defaultInformer(client clientset_internalversion.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHealingRuleInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *healingRuleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&autoheal.HealingRule{}, f.defaultInformer)
}

func (f *healingRuleInformer) Lister() internalversion.HealingRuleLister {
	return internalversion.NewHealingRuleLister(f.Informer().GetIndexer())
}
