/*
Copyright (c) 2018 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	autoheal "github.com/openshift/autoheal/pkg/apis/autoheal"
	scheme "github.com/openshift/autoheal/pkg/client/clientset/internalversion/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HealingRulesGetter has a method to return a HealingRuleInterface.
// A group's client should implement this interface.
type HealingRulesGetter interface {
	HealingRules(namespace string) HealingRuleInterface
}

// HealingRuleInterface has methods to work with HealingRule resources.
type HealingRuleInterface interface {
	Create(*autoheal.HealingRule) (*autoheal.HealingRule, error)
	Update(*autoheal.HealingRule) (*autoheal.HealingRule, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*autoheal.HealingRule, error)
	List(opts v1.ListOptions) (*autoheal.HealingRuleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *autoheal.HealingRule, err error)
	HealingRuleExpansion
}

// healingRules implements HealingRuleInterface
type healingRules struct {
	client rest.Interface
	ns     string
}

// newHealingRules returns a HealingRules
func newHealingRules(c *AutohealClient, namespace string) *healingRules {
	return &healingRules{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the healingRule, and returns the corresponding healingRule object, and an error if there is any.
func (c *healingRules) Get(name string, options v1.GetOptions) (result *autoheal.HealingRule, err error) {
	result = &autoheal.HealingRule{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("healingrules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HealingRules that match those selectors.
func (c *healingRules) List(opts v1.ListOptions) (result *autoheal.HealingRuleList, err error) {
	result = &autoheal.HealingRuleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("healingrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested healingRules.
func (c *healingRules) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("healingrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a healingRule and creates it.  Returns the server's representation of the healingRule, and an error, if there is any.
func (c *healingRules) Create(healingRule *autoheal.HealingRule) (result *autoheal.HealingRule, err error) {
	result = &autoheal.HealingRule{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("healingrules").
		Body(healingRule).
		Do().
		Into(result)
	return
}

// Update takes the representation of a healingRule and updates it. Returns the server's representation of the healingRule, and an error, if there is any.
func (c *healingRules) Update(healingRule *autoheal.HealingRule) (result *autoheal.HealingRule, err error) {
	result = &autoheal.HealingRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("healingrules").
		Name(healingRule.Name).
		Body(healingRule).
		Do().
		Into(result)
	return
}

// Delete takes name of the healingRule and deletes it. Returns an error if one occurs.
func (c *healingRules) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("healingrules").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *healingRules) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("healingrules").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched healingRule.
func (c *healingRules) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *autoheal.HealingRule, err error) {
	result = &autoheal.HealingRule{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("healingrules").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
